# version: '3.8'

# services:
#   nestjs-app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"
#     networks:
#       - monitoring-network

#   prometheus:
#     image: prom/prometheus:latest
#     ports:
#       - "9090:9090"
#     volumes:
#       - ./prometheus.yml:/etc/prometheus/prometheus.yml
#     command:
#       - '--config.file=/etc/prometheus/prometheus.yml'
#     networks:
#       - monitoring-network

# networks:
#   monitoring-network:
#     driver: bridge 

version: '3.8'

services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nestjs-prometheus-app:latest
    container_name: nestjs-prometheus-container
    # ports:   # enable it whn debugging
    #   - "3000:3000"
    networks:
      - monitoring-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - monitoring-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      # - grafana-storage:/var/lib/grafana
      - ./grafana-data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards/nestjs-dashboard.json:/etc/grafana/provisioning/dashboards/nestjs-dashboard.json
    networks:
      - monitoring-network
    depends_on:
      - prometheus
      - nestjs-app

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    ports:
      - "9113:9113"
    command:
      - -nginx.scrape-uri=http://nginx/stub_status
    networks:
      - monitoring-network
    depends_on:
      nginx:
        condition: service_healthy

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - monitoring-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - prometheus
      - nestjs-app

# volumes:
#   grafana-storage:

networks:
  monitoring-network:
    driver: bridge