global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nestjs'
    static_configs:
      - targets: ['nestjs-app:3000']
    metrics_path: '/metrics'
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113'] 